### ISSUE TITLE
提取失败

### ISSUE THREAD

**Issue by sunbin-gh** [CyanideCN/HorcruxCollegeExtract#2]
按照python命令执行文件无效，建议能否生成exe格式。谢谢

**Comment by Dingoen** [comment]
@CyanideCN 我用python3.8的pyinstaller3.5尝试着编译了一下，报错TypeError: an integer is required (got type bytes)，我完全是python小白不太懂这些，请问能不能帮忙编译成exe文件？我的qq是745878792，希望大佬有时间回复我一下或者把编译的exe文件发邮件给我，感激不尽！

**Comment by CyanideCN** [comment]
@Dingo-V 不是让你编译python文件，是让你编译C。那个python脚本只是起辅助作用的，不是解密的主体部分。
